name = "ChiralGraphs"
uuid = "d308c657-c1ba-41ac-9522-b270b0cac06f"
authors = ["Tim Holy", "Casey Kneale"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
